"""Decided to move number_of_pages to user_books as it makes more sense design-wise and to fix bugs.

Revision ID: 5116a4cc0d76
Revises: 07b460742caf
Create Date: 2025-05-15 15:17:19.187742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5116a4cc0d76'
down_revision = '07b460742caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('number_of_pages')

    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_books', schema=None) as batch_op:
        batch_op.drop_column('number_of_pages')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pages', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
